name: hcmv_benchmark
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - R=3.5.1
  - fastp=0.19.4
  - bwa=0.7.17
  - csvtk=0.18.2
  - samtools=1.9
  - bcftools=1.9
  - varscan=2.4.3
  - freebayes=1.2.0
  - lofreq=2.1.3.1
  - picard=2.18.2
  - abyss=2.1.4
  - megahit=1.1.3
  - idba=1.1.3
  - SPAdes=3.12.0
  - Ray=2.3.1
  - bbmap=37.99
  - disco=1.2
  - quast=5.0.2
  - mummer=3.23
  - pip=19.1.1
  - pandas=0.24.2
  - r-tidyverse=1.2.1
  - r-cowplot=0.9.4
  - r-reshape2=1.4.3
  - r-venndiagram=1.6.20
  - r-gridextra=2.3
  - r-dplyr=0.8.1
  - r-pheatmap=1.0.12
  - r-NMF=0.21.0
  - r-ggdendro=0.1_20
  - r-rcolorbrewer=1.1_2
  - r-devtools=2.2.1
  - bioconductor-biocinstaller=1.32.1
  - bioconductor-somaticsignatures=2.18.0
  - bioconductor-mutationalpatterns=1.8.0
  - bioconductor-somaticcanceralterations=1.18.0
