samplesDesc: config/sample_list.tsv
MerlinRef: ref/Merlin.BAC.fa
TB40ERef: ref/TB40E.GFP.fa
AD169Ref: ref/AD169.BAC.fa
PhixRef: ref/Phix.fa
outpath: ../revision_output_4
threads: 20
runOnReads: false
rmHumanEcoli: true
HumanRefBWAIdx: /net/sgi/viral_genomics/MHH/human_genome/hg19.genome.bwa
EcoliRefBWAIdx: ref/Ecoli.NC_000913.fa
