samplesDesc: config/sample_list.tsv
MerlinRef: ref/Merlin.BAC.fa
TB40ERef: ref/TB40E.GFP.fa
AD169Ref: ref/AD169.BAC.fa
PhixRef: ref/Phix.fa
outpath: ../HCMV_benchmark_output_test
threads: 2
runOnReads: false
